// server.js
// Fallback/wrapper script for Plesk Node.js extension (Phusion Passenger)
const path = require('path');

process.env.NODE_ENV = 'production';
process.env.PORT = process.env.PORT || 3000;

try {
  // Try to load the standalone server generated by Next.js build
  require('./.next/standalone/server.js');
} catch (error) {
  console.error('Next.js standalone server could not be started.');
  console.error('Please ensure the project is built using "npm run build" first.');
  console.error('Error details:', error.message);
  process.exit(1);
}
